name = "worker-badge"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "e8ff9c2855e44e717fff487f7627b58f"
workers_dev = true
kv-namespaces = [ 
    { binding = "badgeKV", id = "f30cab6849f94377817939fb4acbc559", preview_id = "62c36c2bf8bc4ef78ea69fe2e83a10f4"} 
]
vars = { GITHUB_TOKEN = "update this value" }

[env.staging]
name = "badge-staging"
zone_id = "6b88c22fc374b7fcb114cbefe6b534e1"
route = "staging.webadge.dev/*"
kv-namespaces = [ 
    { binding = "badgeKV", id = "c5879b398e7e46888a48f7f7e836e868" } 
]

[env.production]
name = "badge-production"
zone_id = "6b88c22fc374b7fcb114cbefe6b534e1"
route = "webadge.dev/*"
kv-namespaces = [ 
    { binding = "badgeKV", id = "c17aac01aa874306be3474471bf84925" } 
]